### ISSUE TITLE
Local inference on A6000?

### ISSUE THREAD

**Issue by caseybasichis** [magenta/music-spectrogram-diffusion#13]
I'd love to test this out on my system -- any hope?

I was working on installing the collab dependencies locally, but I'm stuck here.
sed -i 's:jax\[tpu\]:jax:' setup.py

**Comment by cghawthorne** [comment]
You can probably skip that line. The important thing is that you end up with a version of JAX installed that has support for your GPU: https://github.com/google/jax#pip-installation-gpu-cuda
