### ISSUE TITLE
XlaRuntimeError: INVALID_ARGUMENT: Computation requires more parameters (424) than supported (limit 237).

### ISSUE THREAD

**Issue by pmartins2022** [magenta/music-spectrogram-diffusion#9]
Yesterday I ran the colab notebook just fine. Today it's getting en error in the last stage of execution (Synthesize Audio).

Stack Trace:

`/usr/local/lib/python3.7/dist-packages/flax/core/scope.py:741: FutureWarning: jax.tree_leaves is deprecated, and will be removed in a future release. Use jax.tree_util.tree_leaves instead.
  value_flat = jax.tree_leaves(value)
/usr/local/lib/python3.7/dist-packages/flax/core/scope.py:740: FutureWarning: jax.tree_leaves is deprecated, and will be removed in a future release. Use jax.tree_util.tree_leaves instead.
  abs_value_flat = jax.tree_leaves(abs_value)
/usr/local/lib/python3.7/dist-packages/flax/core/scope.py:741: FutureWarning: jax.tree_leaves is deprecated, and will be removed in a future release. Use jax.tree_util.tree_leaves instead.
  value_flat = jax.tree_leaves(value)
/usr/local/lib/python3.7/dist-packages/flax/core/scope.py:740: FutureWarning: jax.tree_leaves is deprecated, and will be removed in a future release. Use jax.tree_util.tree_leaves instead.
  abs_value_flat = jax.tree_leaves(abs_value)
/usr/local/lib/python3.7/dist-packages/flax/core/scope.py:741: FutureWarning: jax.tree_leaves is deprecated, and will be removed in a future release. Use jax.tree_util.tree_leaves instead.
  value_flat = jax.tree_leaves(value)
/usr/local/lib/python3.7/dist-packages/flax/core/scope.py:740: FutureWarning: jax.tree_leaves is deprecated, and will be removed in a future release. Use jax.tree_util.tree_leaves instead.
  abs_value_flat = jax.tree_leaves(abs_value)
/usr/local/lib/python3.7/dist-packages/flax/core/scope.py:741: FutureWarning: jax.tree_leaves is deprecated, and will be removed in a future release. Use jax.tree_util.tree_leaves instead.
  value_flat = jax.tree_leaves(value)
---------------------------------------------------------------------------
UnfilteredStackTrace                      Traceback (most recent call last)
[<ipython-input-8-9c5807f2c0fb>](https://localhost:8080/#) in <module>
     33           batch['encoder_continuous_mask'])
---> 34     pred_mel, scores = synth_model.predict(batch)
     35     full_pred_mel = np.concatenate([full_pred_mel, pred_mel[:1]], axis=1)

17 frames
[/content/music_spectrogram_diffusion/inference.py](https://localhost:8080/#) in predict(self, batch, seed)
    202     predict_fn, params = self._get_predict_fn_and_params()
--> 203     return predict_fn(params, batch, jax.random.PRNGKey(seed))

[/content/t5x/partitioning.py](https://localhost:8080/#) in __call__(self, *args)
    753                   self._logical_axis_rules):
--> 754       return self._pjitted_fn(*args)
    755 

[/usr/local/lib/python3.7/dist-packages/jax/_src/traceback_util.py](https://localhost:8080/#) in reraise_with_filtered_traceback(*args, **kwargs)
    161     try:
--> 162       return fun(*args, **kwargs)
    163     except Exception as e:

[/usr/local/lib/python3.7/dist-packages/jax/_src/api.py](https://localhost:8080/#) in cache_miss(*args, **kwargs)
    530         device=device, backend=backend, name=flat_fun.__name__,
--> 531         donated_invars=donated_invars, inline=inline, keep_unused=keep_unused)
    532     out_pytree_def = out_tree()

[/usr/local/lib/python3.7/dist-packages/jax/core.py](https://localhost:8080/#) in bind(self, fun, *args, **params)
   1962   def bind(self, fun, *args, **params):
-> 1963     return call_bind(self, fun, *args, **params)
   1964 

[/usr/local/lib/python3.7/dist-packages/jax/core.py](https://localhost:8080/#) in call_bind(primitive, fun, *args, **params)
   1978   fun_ = lu.annotate(fun_, fun.in_type)
-> 1979   outs = top_trace.process_call(primitive, fun_, tracers, params)
   1980   return map(full_lower, apply_todos(env_trace_todo(), outs))

[/usr/local/lib/python3.7/dist-packages/jax/core.py](https://localhost:8080/#) in process_call(self, primitive, f, tracers, params)
    688   def process_call(self, primitive, f, tracers, params):
--> 689     return primitive.impl(f, *tracers, **params)
    690   process_map = process_call

[/usr/local/lib/python3.7/dist-packages/jax/_src/dispatch.py](https://localhost:8080/#) in _xla_call_impl(***failed resolving arguments***)
    233   compiled_fun = xla_callable(fun, device, backend, name, donated_invars,
--> 234                               keep_unused, *arg_specs)
    235   try:

[/usr/local/lib/python3.7/dist-packages/jax/linear_util.py](https://localhost:8080/#) in memoized_fun(fun, *args)
    294     else:
--> 295       ans = call(fun, *args)
    296       cache[key] = (ans, fun.stores)

[/usr/local/lib/python3.7/dist-packages/jax/_src/dispatch.py](https://localhost:8080/#) in _xla_callable_uncached(fun, device, backend, name, donated_invars, keep_unused, *arg_specs)
    324     return lower_xla_callable(fun, device, backend, name, donated_invars, False,
--> 325                               keep_unused, *arg_specs).compile().unsafe_call
    326 

[/usr/local/lib/python3.7/dist-packages/jax/_src/dispatch.py](https://localhost:8080/#) in compile(self)
    935             self.name, self._hlo, self._in_type, self._out_type,
--> 936             **self.compile_args)
    937 

[/usr/local/lib/python3.7/dist-packages/jax/_src/dispatch.py](https://localhost:8080/#) in from_xla_computation(name, xla_computation, in_type, out_type, nreps, device, backend, tuple_args, in_avals, out_avals, has_unordered_effects, ordered_effects, kept_var_idx, keepalive, host_callbacks)
   1052       compiled = compile_or_get_cached(backend, xla_computation, options,
-> 1053                                        host_callbacks)
   1054     buffer_counts = get_buffer_counts(out_avals, ordered_effects,

[/usr/local/lib/python3.7/dist-packages/jax/_src/dispatch.py](https://localhost:8080/#) in compile_or_get_cached(backend, computation, compile_options, host_callbacks)
   1005     _dump_ir_to_file(module_name, ir_str)
-> 1006   return backend_compile(backend, computation, compile_options, host_callbacks)
   1007 

[/usr/local/lib/python3.7/dist-packages/jax/_src/profiler.py](https://localhost:8080/#) in wrapper(*args, **kwargs)
    312     with TraceAnnotation(name, **decorator_kwargs):
--> 313       return func(*args, **kwargs)
    314     return wrapper

[/usr/local/lib/python3.7/dist-packages/jax/_src/dispatch.py](https://localhost:8080/#) in backend_compile(backend, built_c, options, host_callbacks)
    949   # to take in `host_callbacks`
--> 950   return backend.compile(built_c, compile_options=options)
    951 

UnfilteredStackTrace: jaxlib.xla_extension.XlaRuntimeError: INVALID_ARGUMENT: Computation requires more parameters (424) than supported (limit 237).

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

XlaRuntimeError                           Traceback (most recent call last)
[<ipython-input-8-9c5807f2c0fb>](https://localhost:8080/#) in <module>
     32       batch['encoder_continuous_mask'] = np.ones_like(
     33           batch['encoder_continuous_mask'])
---> 34     pred_mel, scores = synth_model.predict(batch)
     35     full_pred_mel = np.concatenate([full_pred_mel, pred_mel[:1]], axis=1)
     36     i += 1

[/content/music_spectrogram_diffusion/inference.py](https://localhost:8080/#) in predict(self, batch, seed)
    201     """Predict tokens from preprocessed dataset batch."""
    202     predict_fn, params = self._get_predict_fn_and_params()
--> 203     return predict_fn(params, batch, jax.random.PRNGKey(seed))

[/content/t5x/partitioning.py](https://localhost:8080/#) in __call__(self, *args)
    752               self._mesh.axis_names), flax_partitioning.axis_rules(
    753                   self._logical_axis_rules):
--> 754       return self._pjitted_fn(*args)
    755 
    756   def lower(self, *args):

XlaRuntimeError: INVALID_ARGUMENT: Computation requires more parameters (424) than supported (limit 237).`

![image](https://user-images.githubusercontent.com/102955033/187767352-e1eb4524-85d7-4c37-ae41-0899c3d5add4.png)

**Comment by cghawthorne** [comment]
I'm not sure what would cause that. Does the error persist if you do "Runtime, disconnect and delete runtime" and then try again? I wonder if the attached host/TPU got in a weird state.

**Comment by pmartins2022** [comment]
> I'm not sure what would cause that. Does the error persist if you do "Runtime, disconnect and delete runtime" and then try again? I wonder if the attached host/TPU got in a weird state.

It must have been a host issue. I did not try to delete the runtime, I just restarted it. I will try again later today, thanks.

**Comment by pmartins2022** [comment]
I tried again using 3 different hosts, all failed in the last step.
The console output would just print "generated segment x", now it prints hundreds of 'WARNING:absl:' warnings for a few minutes and then stops with the same error everytime.

`WARNING:absl:Since rank of parameter continuous_encoder/layers_10/mlp/wo/kernel 2 is less than or equal to 2, the factorization method falls back to heuristics and the provided factor rule (<FactorDim.COLUMN: 3>, <FactorDim.ROW: 2>) is ignored.
WARNING:absl:Since rank of parameter continuous_encoder/layers_10/pre_attention_layer_norm/scale 1 is less than or equal to 2, the factorization method falls back to heuristics and the provided factor rule (<FactorDim.NONE: None>,) is ignored.
WARNING:absl:Since rank of parameter continuous_encoder/layers_10/pre_mlp_layer_norm/scale 1 is less than or equal to 2, the factorization method falls back to heuristics and the provided factor rule (<FactorDim.NONE: None>,) is ignored.
WARNING:absl:Since rank of parameter continuous_encoder/layers_11/attention/key/kernel 2 is less than or equal to 2, the factorization method falls back to heuristics and the provided factor rule (<FactorDim.ROW: 2>, <FactorDim.COLUMN: 3>) is ignored.

/usr/local/lib/python3.7/dist-packages/flax/linen/partitioning.py:122: FutureWarning: jax.tree_leaves is deprecated, and will be removed in a future release. Use jax.tree_util.tree_leaves instead.
  existing = set(jax.tree_leaves(existing_assignments))
WARNING:absl:Tiling device assignment mesh by hosts, which may lead to reduced XLA collective performance. To avoid this, modify the model parallel submesh or run with more tasks per host.
/content/t5x/checkpoints.py:158: FutureWarning: jax.tree_flatten is deprecated, and will be removed in a future release. Use jax.tree_util.tree_flatten instead.
  future_leaves, treedef = jax.tree_flatten(future_tree)
/content/t5x/checkpoints.py:163: FutureWarning: jax.tree_unflatten is deprecated, and will be removed in a future release. Use jax.tree_util.tree_unflatten instead.
  return jax.tree_unflatten(treedef, leaves)`

These are the last output lines before it crashes.

Could you look into this? It must be reproducible every time.

**Comment by cghawthorne** [comment]
Confirmed that I can reproduce the problem. @iansimon can you take a look at this while I'm out?

**Comment by cghawthorne** [comment]
Turned out not to be too difficult to fix. JAX released a new pip package yesterday, which apparently broke things. We're using a kind of weird setup in the colab notebook due to Python 3.7 and the old way colab accesses TPUs, so I'm not too surprised something broke. I'll have it fixed shortly.

**Comment by cghawthorne** [comment]
Oh and thanks for reporting the issue!
